### ISSUE TITLE
with redis option socket-anti-spam not working 

### ISSUE THREAD

**Issue by hsngerami** [michaeldegroot/socket-anti-spam#38]
When i used redis option, socket.io not working and show this error in console. but when i don't used redis option, it's worked.
`(node:17105) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '127.0.0.1' of null
    at Promise (/home/hossein/Develop/js/projects/indigo/node_modules/socket-anti-spam/antispam.js:122:28)
    at new Promise (<anonymous>)
    at SocketAntiSpam.authenticate (/home/hossein/Develop/js/projects/indigo/node_modules/socket-anti-spam/antispam.js:116:12)
    at Namespace.SocketAntiSpam.sets.io.on (/home/hossein/Develop/js/projects/indigo/node_modules/socket-anti-spam/antispam.js:52:14)
    at Namespace.emit (events.js:185:15)
    at Namespace.emit (/home/hossein/Develop/js/projects/indigo/node_modules/socket.io/lib/namespace.js:213:10)
    at /home/hossein/Develop/js/projects/indigo/node_modules/socket.io/lib/namespace.js:181:14
    at process._tickCallback (internal/process/next_tick.js:112:11)
(node:17105) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17105) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by fessnecro** [comment]
have same problem...

**Comment by mrwillis** [comment]
Check out my fork a fix. It uses redis properly. The problem here is that on a fresh redis, there is no data, so you get null on the first `redisRead`. Moreover, this code never reads from redis, so if it is horizontally scaled, data won't be shared. Check out my fork for a fix:

https://github.com/mrwillis/socket-io-anti-spam
